services:
  order-service:
    build: .
    image: order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/orders
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8085:8080"
    networks:
      - application-network

networks:
  application-network:
    external: true
    name: application-network